namespace allorders.db;

@cds.persistence.exists

entity![ORDERS]{
    key![SalesOrder]             : String(10);
       ![SalesOrderItem]         : String(6);
       ![CreatedOn]              : Date;
       ![MaterialNo]             : String(18);
       ![MaterialName]           : String(40);
       ![SoldToParty]            : String(10);
       ![SoldtoPartyName]        : String(40);
       ![ShipToParty]            : String(10);
       ![ShipToPartyName]        : String(40);
       ![CustomerReference]      : String(35);
       ![SalesOrg]               : String(4);
       ![SalesOrgName]           : String(20);
       ![Note]                   : String(255);
       ![RequestedDelDate]       : Date;
       ![RequestedQuantity]      : Decimal(15, 3);
       ![RequestedQuantityUnit]  : String(3);
       ![Plant]                  : String(4);
       ![OrderType]              : String(4);
       ![OrderTypeDesc]          : String(20);
       ![POType]                 : String(4);
       ![POTypeDesc]             : String(20);
       ![Incoterm1]              : String(3);
       ![Incoterm2]              : String(28);
       ![PaymentTerm]            : String(4);
       ![VEPartner]              : String(8);
       ![VEPartnerName]          : String(40);
       ![ASPartner]              : String(8);
       ![ASPartnerName]          : String(40);
       ![DIFF_CONF_REQ_DATE]     : String(8);
       ![GROUP_COMPANY]          : String(1);
       ![SUPPLY_POINT]          : String(1);
       ![CUSTOMER_PRIORITY]      : String(30);
       ![TM_DOC_NO]              : String(10);
       ![FORWARDER_NAME]         : String(35);
       ![VESSEL_NAME]            : String(35);
       ![CONTAINER_NO]           : String(20);
       ![ShipmentETA]            : Date;
       ![ShipmentETD]            : Date;
       ![ConfDelDate]            : Date;
       ![SHIPPING_TYPE]          : String(2);
       ![SHIP_TYPE_DESC]         : String(20);
       ![LoadingDate]            : Date;
       ![SHIP_STAT_DESC]         : String(255);
       ![SHIP_STATR_DESC]        : String(255);
       ![REQ_TEXT]               : String(250);
       ![BILLING_BLOCK_ITEM]     : String(250);
       ![DOCUMENT_TYPE]          : String(1);
       ![GUSCON_LEVEL]           : String(2);
       ![LEVEL_TYPE]             : String(7);
       ![SORT_ORDER]             : Integer;
       ![ORDER_STATUS]           : String(12);
       ![DISTRIBUTION_CHANNEL]   : String(2);
       ![DELIVERY]               : String(10);
       ![SBU]                    : String(18);
       ![PlannedDelDate]         : Date;
       ![SORT_ORDER1]            : Integer;
       ![INITIAL_ORDER]          : String(10);
       ![NEXT_ORDER]             : String(10);
       ![FINAL_ORDER]            : String(10);
       ![STATUS_BIZAGI]          : String(100);
       ![FA_TRACKING_ID]         : String(35);
       ![TRACKING_ID]            : String(12);
       ![LC_NUMBER]              : String(10);
       ![CUSTOMER_MAT_REFERENCE] : String(100);
       ![CONFIRMED_QUANTITY]     : Decimal(15, 3);
       ![PENDING_DEL_QTY]        : Decimal(15, 3);
       ![PENDING_DEL_QTY_UNIT]   : String(3);
       ![UNCONFIRMED_QUANTITY]   : Decimal(15, 3);
       ![DELIVERY_TYPE]          : String(40);
       ![STORAGE_LOCATION]       : String(4);
       ![SUPPLYING_PLANT]        : String(4);
       ![SELLING_INVOICE]        : String(10);
       ![CREATION_DATE]          : Date;
       ![SHIP_TO_COUNTRY_NAME]   : String(25);
       ![SUPPLY_SITUATION]       : String(50);
       ![DELIVERY_QTY]           : Decimal(15, 3);
       ![SUPPLIER_PO]            : String(35);
       ![COM_TRACKING_ID]        : String(50);
       ![PRICING_DATE]           : Date;
       ![BILLING_DOCUMENT]       : String(10);
       ![DEL_QTY_UNIT]           : String(3);
       ![CO_PARTNER]             : String(10);
       ![CO_PARTNER_NAME]        : String(40);
       ![NY_PARTNER]             : String(10);
       ![NY_PARTNER_NAME]        : String(40);
       ![SHIPMNT_ATA]            : Date;
       ![SHIPMNT_ATD]            : Date;
       ![ShipmentATA]            : Date;
       ![ShipmentATD]            : Date;
       ![BATCH_NUMBER]           : String(10);
       ![DATE_OF_MANUF]          : Date;
       ![SHELF_LIFE_EXP_DATE]    : Date;
       ![NOTA_FISCAL]            : String(16);
       ![AM_PARTNER]             : String(10);
       ![AM_PARTNER_NAME]        : String(40);
       ![NET_AMOUNT]             : String(25);
       ![PRICE_PER_UNIT]         : String(30);
       ![MRP_CONTROLLER]         : String(3);
       ![ITEM_CATEGORY]          : String(30);
       ![HOM_REMARK]             : String;
       ![SHIP_TO_CITY_NAME]      : String(40);
       ![PROD_ALLOC]             : String(18)


}
